"""create mars_explorations
Revision ID: ffba5f9a2b85
Revises: 
Create Date: 2026-04-28 21:33:02.347377
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ffba5f9a2b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for safe conversions ###
    # convert textual booleans to proper boolean using a CASE expression
    op.alter_column(
        'mars_explorations',
        'is_favorite',
        existing_type=sa.VARCHAR(length=5),
        type_=sa.Boolean(),
        existing_nullable=False,
        postgresql_using=(
                "CASE WHEN lower(is_favorite::text) IN ('t','true','1') THEN true "
                "WHEN lower(is_favorite::text) IN ('f','false','0') THEN false ELSE NULL END"
        ),
    )

    # convert textual timestamps to proper timestamp without time zone
    op.alter_column(
        'mars_explorations',
        'created_at',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DateTime(),
        existing_nullable=False,
        postgresql_using="created_at::timestamp",
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mars_explorations', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('mars_explorations', 'is_favorite',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
